<?xml version="1.0" encoding="utf-8"?><Database Name="inventry" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MININT-8DSL3GL;Initial Catalog=inventry;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="inventryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProdDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Addproduct" Method="Addproduct">
    <Parameter Name="param1" Type="System.Int32" DbType="Int" />
    <Parameter Name="param2" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="param3" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Return Type="System.Int32" />
  </Function>
</Database>